version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - STORAGE=postgres
      - DB=user=postgres dbname=urlshort sslmode=disable
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: urlshort
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
